[rocm-libraries] ROCm/rocm-libraries#1505 (commit 3429a2c)
Fix build warning in rocprim

## Motivation

The current code gives a build warning in rocprim with rocm 7.0:
```
/pipeline/amd/libraries/rocm-libraries/projects/rocprim/rocprim/include/rocprim/device/detail/lookback_scan_state.hpp:628:26: error: first argument in call to '__builtin_memcpy' is a pointer to non-trivially copyable type 'test_utils::custom_test_array_type<int, 10>' [-Werror,-Wnontrivial-memcall]
  628 |         __builtin_memcpy(&value, &v, sizeof(value));
```

## Technical Details

Used a reinterpret_cast to void* to silence this warning. It showed no
change in assembly output.

## Test Plan

It should no longer give this warning with rocm 7.0.

## Test Result

It should no longer give this warning in rocm 7.0.

## Submission Checklist

- [ ] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

Co-authored-by: Wayne Franz <wayfranz@amd.com>