Add Hip-Cpu support initial (#233)
* Update benchmark config tuning code

* Move options up front

* Remove DISABLE_WERROR option

* Update summary

* Add to README as experimental back-end

* IMPORTED target based dependency definition

* [HIP-CPU] MSVC: error C1128 (/bigobj)

* [HIP-CPU] CUDA-style indexing and kernel launch

* [HIP-CPU] ambiguous call to overloaded function

* cannot convert argument 1 from 'T **' to 'void **'

* [HIP-CPU] unknown pragma 'unroll'

* [HIP-CPU] half has explicit CTOR

* [HIP-CPU] MSVC: 'name' hides previous declaration

* [HIP-CPU] MSVC: error C2975

* [HIP-CPU] MSVC: C2365 (redefinition of symbol)

* [HIP-CPU] rocprim::half_native for plats w/o one

* [HIP-CPU] ISO C++ alignment specification

* TYPED_TEST_CASE is deprecated

* Silence conversion warning

* [HIP-CPU] Note on optimization opportunity

* uniform_int_distribution is undefined for (u)int8

* [HIP-CPU] omit texture support

* [HIP-CPU] MSVC: expr SFINAE bug on auto ret type

* [HIP-CPU] Type check too strict. (Diagnostic only)

* [HIP-CPU] Empty binary op for dummy operations

* [HIP-CPU] Zero out potentially used uninit storage

* More easily replacable PRNG engine

* [HIP-CPU] MSVC: function isn't constexpr enough

* [HIP-CPU] MSVC: error C2440

* [HIP-CPU] MSVC: workaround

* [HIP-CPU] Port of clang/hipcc intrinsics

* [HIP-CPU] MSVC: STL misuse fix (C4996)

* [HIP-CPU] Fix various conversion warnings

* ambiguous call to function

* [HIP-CPU] Guard against missing header

* Add missing utility funtion for MSVC

* Add distinct default type

* Potential use of uninitialized storage

* [HIP-CPU] Strictly ISO conforming overload control

* Erronous use of token paste preprocessor operator

* Define-friendly pragma (no)unroll

* Refrain from C++17 utility std::disjunction

* [HIP-CPU] libstdc++: Depend on TBB unconditionally

* [HIP-CPU] GCC: Preliminary impl of __lastbit

* [HIP-CPU] Hotfix lack of dpp built-ins

* error: attributes are not allowed on a function-definition

* Fix rebase error

* Extend lane_mask_type to non-hipcc compilers

* [HIP-CPU] Host compiler pretend to be hipcc

* [HIP-CPU] GCC: decl of x changes meaning of symbol

* [HIP-CPU] CI testing HIP-CPU build only

* Temporarily reroute to HIP-CPU fork

* error C3861: 'uint': identifier not found

* error C3861: 'min': identifier not found

* disambiguate function call

* ISO C++ alignment specification

* Prevent shared memory from slipping to size == 0

* Bump GTest version dep

* Inherit build and library type

* Issue error when using multi-conf gen with dep mgt

* Downgrade TBB dependence to match libstc++

* [HIP-CPU] GCC: Circumvent load/store_volatile

* [HIP-CPU] Remove static_assert type-check

* [HIP-CPU] MSVC: Guard against inline asm

* [HIP-CPU] Clang/hipcc: use diff half impls

* Reinstantiate -Werror via CI script

* Removed unused local type aliases

* [HIP-CPU] Revert to original comparator with fix

* Remove implicit cast (truncation)

* [HIP-CPU] Limit CPU builds to fit runner RAM

* Disable hip-cpu build step from gitlab CI

* Handle size_t in cmdparser.hpp

* Change hip-cpu url

* Added experimental HIP-CPU support to changelog

* Compilation fix for gfx1030

Co-authored-by: Máté Ferenc Nagy-Egri <mate@streamhpc.com>
Co-authored-by: Stanley Tsang <stanley.tsang@amd.com>