[rocm-libraries] ROCm/rocm-libraries#5637 (commit dd6042e)
feat(primbench): make AMD SMI and NVML soft dependencies
 (#5637)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

## Motivation

The PR [[rocPRIM] Warn/Prevent rocPRIM benchmarks from being built on
Windows](https://github.com/ROCm/rocm-libraries/pull/5494) was merged as
a hotfix, since rocPRIM's benchmarks were not buildable on Windows
anymore.

This PR its commit `fix(rocprim): revert Windows hotfix PR #5494`
reverts that hotfix, and provides a *proper* fix, by turning AMD SMI and
NVML from hard dependencies into soft dependencies.

This PR will be undrafted once the PR [feat(primbench): support an extra
backend](https://github.com/ROCm/rocm-libraries/pull/5512) on which it
is based has been merged.

## Technical Details

[Here](https://github.com/ROCm/rocm-libraries/tree/users/mynameistrez/make-amdsmi-and-nvml-soft-dependencies/shared/primbench#dependencies)
is the updated Dependencies section of the readme:

<img width="1353" height="755" alt="image"
src="https://github.com/user-attachments/assets/ff8b98b5-1d1c-4fae-a6be-fd2ee7e7415c"
/>

## Test Plan

### VS Code dev containers

<details>
<summary>CUDA <code>Dockerfile</code> +
<code>devcontainer.json</code></summary>

`Dockerfile`:
```Dockerfile
FROM nvidia/cuda:12.9.1-devel-ubuntu24.04

RUN apt update && apt install -y git cmake ninja-build wget

RUN wget -qO- https://repo.radeon.com/rocm/rocm.gpg.key | gpg --dearmor > /etc/apt/keyrings/rocm.gpg

RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/7.2 noble main" > /etc/apt/sources.list.d/rocm.list

RUN tee /etc/apt/preferences.d/rocm-pin-600 <<'EOF'
Package: *
Pin: origin repo.radeon.com
Pin-Priority: 600
EOF

RUN apt update && apt install -y hip-base

ENV HIP_PLATFORM=nvidia
```

`devcontainer.json`:
```json
{
    "build": {
        "dockerfile": "Dockerfile"
    },
    "name": "cuda-minimal",
    "privileged": true,
    "runArgs": [
        "--gpus=all"
    ]
}
```

</details>

<details>
<summary>HIP <code>Dockerfile</code> +
<code>devcontainer.json</code></summary>

`Dockerfile`:
```Dockerfile
FROM rocm/rocm-terminal:latest
```

`devcontainer.json`:
```json
{
    "build": {
        "dockerfile": "Dockerfile"
    },
    "name": "hip-minimal",
    "runArgs": [
        "--device=/dev/kfd",
        "--device=/dev/dri"
    ]
}
```

</details>

## Test Result

I have confirmed that Stream HPC's CI is now able to build rocPRIM's
benchmarks on Windows. It is crucial however for AMD's CI, or one of
AMD's reviewers, to confirm that rocPRIM's benchmarks now build and run
successfully on Windows for them too.

<details>
<summary>Monitoring still works</summary>

```sh
hipcc -o copy_benchmark examples/hip/copy_benchmark.cpp -I. -lamd_smi && ./copy_benchmark --json-out monitoring.json --csv-out monitoring.csv
```
```sh
nvcc -o copy_benchmark examples/cuda/copy_benchmark.cu -I. -lnvidia-ml && ./copy_benchmark --json-out monitoring.json --csv-out monitoring.csv
```

</details>

<details>
<summary>Monitoring can now be turned off</summary>

```sh
hipcc -o copy_benchmark examples/hip/copy_benchmark.cpp -I. -DPRIMBENCH_NO_MONITORING && ./copy_benchmark --json-out no_monitoring.json --csv-out no_monitoring.csv
```
```sh
nvcc -o copy_benchmark examples/cuda/copy_benchmark.cu -I. -DPRIMBENCH_NO_MONITORING && ./copy_benchmark --json-out no_monitoring.json --csv-out no_monitoring.csv
```

When monitoring is disabled, the `GPU °C` column is excluded from the
printed output:
```
Status of copy             Noise  Bytes/sec  Specialization   Index/2
─────────────────────────────────────────────────────────────────────
Success after 1s            0.1%   4.08e+11  type: char             0
Success after 1s            0.0%   5.33e+11  type: long long        1
```

The `monitoring`, `temperature_type` and `gpu_temp_celcius` keys are
also excluded from the JSON output:
```diff
23,27d22
<             "monitoring": {
<                 "name": "amdsmi",
<                 "version": "25.3.0"
<             },
<             "temperature_type": "edge",
73,76d67
<             },
<             "gpu_temp_celsius": {
<                 "start": 50,
<                 "end": 48
```

</details>

<details>
<summary>Forgetting to pass <code>-DPRIMBENCH_NO_MONITORING</code>
throws documented compilation errors</summary>

```sh
hipcc -o copy_benchmark examples/hip/copy_benchmark.cpp -I. && ./copy_benchmark
```
```sh
nvcc -o copy_benchmark examples/cuda/copy_benchmark.cu -I. && ./copy_benchmark
```

```
ld.lld: error: undefined symbol: amdsmi_get_lib_version
>>> referenced by copy_benchmark.cpp
```

```
/usr/bin/ld: /tmp/tmpxft_00007baa_00000000-11_copy_benchmark.o: in function `primbench::detail::monitor::get_temp() const':
tmpxft_00007baa_00000000-6_copy_benchmark.cudafe1.cpp:(.text._ZNK9primbench6detail7monitor8get_tempEv[_ZNK9primbench6detail7monitor8get_tempEv]+0x35): undefined reference to `nvmlDeviceGetTemperature'
```

</details>

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.